import type { ProducerType } from '../enums/producer.js';

export interface EvidenceReference {
  readonly uri: string;
  readonly description: string;
}

/**
 * Immutable record of a single occurrence in a Work Item's operational lifecycle.
 * Derived fields (timeline_id, category, alters_state, new_state) are computed
 * from the event_type — they are never stored as part of this structure.
 * Canonical schema: prodops/framework/events/event-instance-schema.md
 */
export interface EventInstance {
  /**
   * Globally unique identifier for this event occurrence.
   * Required format: UUID v7 (time-ordered, no domain semantics).
   * Generated by the producer before any persistence. Maps to CloudEvent.id.
   * Immutable — cannot be reused even after correction (Event.Corrected pattern).
   */
  readonly id: string;
  readonly event_type: string;
  readonly work_item_id: string;
  readonly timestamp: string;
  readonly producer_type: ProducerType;
  readonly producer_identity: string;
  readonly schema_version: string;
  readonly payload?: Readonly<Record<string, unknown>>;
  readonly evidence_references?: ReadonlyArray<EvidenceReference>;
  readonly sequence_number?: number;
  readonly notes?: string;
}
